export const actions = {
  addFavoriteVideo: 'addFavoriteVideo',
  removeFavoriteVideo: 'removeFavoriteVideo',
  addFavoriteVideoWithIcon: 'addFavoriteVideoWithIcon',
  removeFavoriteVideoWithIcon: 'removeFavoriteVideoWithIcon',
  setQuery: 'setQuery',
  setApiParams: 'setApiParams',
  setAnchorEl: 'setAnchorEl',
  setUser: 'setUser',
  toggleDarkMode: 'toggleDarkMode',
  toggleDrawer: 'toggleDrawer',
  toggleProfileMenu: 'toggleProfileMenu',
  toggleLoginDialog: 'toggleLoginDialog',
  setStorageKey: 'setStorageKey',
};
